name: unsplash_app
description: A Flutter project that uses TDD, flutter_bloc, freezed, hive, repository pattern

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  dio: ^3.0.9
  freezed_annotation: ^0.11.0+1
  octo_image: ^0.1.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  disposable_provider: any
  primitive_type_parser: 0.0.2
  equatable: any
  bloc_test: ^5.1.0
  cached_network_image: ^2.2.0+1
  pretty_dio_logger: ^1.1.1
  rxdart: ^0.24.1
  connectivity: '>=0.4.8+6 <2.0.0'
  lightweight_result:
    path: ../lightweight_result
  hooks_riverpod: ^0.6.1
  state_notifier: any
  flutter_hooks: any
  webview_flutter: ^0.3.22+1
  build_context: ^2.0.4
  image_gallery_saver: ^1.5.0
  permission_handler: ^5.0.1+1
  animations: any
  flushbar: ^1.10.4

dev_dependencies:
  freezed: ^0.11.5
  build_runner: 1.10.1
  flutter_test:
    sdk: flutter


dependency_overrides:
  analyzer: 0.39.14
  build_resolvers: 1.3.10
  build_runner: 1.10.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - asset/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
